### ISSUE TITLE
Version 1.6.0 and onward Hook will not fire

### ISSUE THREAD

**Issue by Thedrummonger** [OE100/ReHooked#4]
Starting with Version 1.6.0, pressing the designated hotkey will not fire any hook. I have tested this on both version 1.6.0 and 1.6.1 with no mods installed other than JEI and ReHooked. No errors are present in the Logs.

Minecraft: 1.20.1
Forge: 47.3.0
Rehooked: 1.6.0 - 1.6.1

**Comment by ghost** [comment]
fixed in 1.6.2
