### ISSUE TITLE
NullPointerException crash with ReHooked on NeoForge for 1.21.1

### ISSUE THREAD

**Issue by DenisMasterHerobrine** [OE100/ReHooked#5]
**Minecraft:** 1.21.1
**ReHooked:** 1.7.0-1.21.1
**Adorned (Curios API):** 9.1.4+1.21.0
**NeoForge:** 21.1.83 

## Description
The mod does not even run with NeoForge causing a NullPointerException. Tried to add a mod to an existing modpack, but every time I launch the pack - it crashes.

Created an empty instance with just Adorned and ReHooked and got the same NPE error.

## Expected Behaviour
Mod should launch as expected and not to crash.

## Current Behaviour
Mod crashes with an NPE with `java.lang.NullPointerException` error.
[latest.log](https://github.com/user-attachments/files/17997401/latest.log) (if you find it useful)

**Comment by omergunr100** [comment]
I've just now seen the issue report, I'll try to solve it as soon as I can, thanks for the report

**Comment by omergunr100** [comment]
@DenisMasterHerobrine Uploaded version 1.8.0-1.21.1 to curseforge, the bug should be fixed on the new version.
If you're having any issues with it let me know, and thanks again for the bug report.

**Comment by DenisMasterHerobrine** [comment]
Thank you, now it launches and works as expected!
