### ISSUE TITLE
Having an active hook while changing dimensions grants creative flight

### ISSUE THREAD

**Issue by victorjperez** [OE100/ReHooked#6]
Mod version: `1.7.0-1.20.1`
Minecraft version: `1.20.1`
Forge version: `47.3.0`

Tested with a fresh instance with just Rehooked (and curios)

Hook into a nether portal with any hook like this:
![image](https://github.com/user-attachments/assets/bf0c5066-5a23-4bf2-b55a-7a9556de35d4)
In survival you'll have creative flight.

From looking at the player nbt, it looks like `mayfly` and `flying` being set to `1` is causing this issue, as it gets fixed on death
![image](https://github.com/user-attachments/assets/53bb1594-d7bd-4b7b-9e89-9f7f5eb7bf0a)

**Comment by omergunr100** [comment]
Thanks for the report, I fixed it in version 1.8.0-1.20.1, right now it's only here in the release tab on github, I'll upload it later to cf once I'm done porting it to 1.21.1.

**Comment by omergunr100** [comment]
ok, it's waiting for cf to review and then it'll be up.
thanks again :smile:
