### ISSUE TITLE
[Suggestion] Accessories support

### ISSUE THREAD

**Issue by Aaamorak** [OE100/ReHooked#7]
Currently, the mod requires version `9.1.4` of _**Adorned (Curios)**_, but currently _**Accessories**_ (specifically _**Curios Compat Layer for Accessories**_) only counts as version `9.0.12`.
_**Accessories**_ is a new, reworked alternative to _**Curios**_ and is required by certain mods, you could technically use both _**Curios**_ and _**Accessories**_ simultaneously, but it causes unnecessary clutter.

My suggestion is to change the required version of _**Curios**_ to `9.0.12`, if possible.

**Comment by omergunr100** [comment]
sounds good to me

**Comment by omergunr100** [comment]
![image](https://github.com/user-attachments/assets/eddde737-7494-4ac9-b285-e023a12516ef)
proof of work
